### ISSUE TITLE
ESPAsyncWebServer

### ISSUE THREAD

**Issue by makeSmartio** [Nredor/ESPNexUpload#7] opened 2019-06-22 13:44 UTC
Have you ever tried using ESPAsyncWebServer instead of the standard webserver for the uploadServer option? I am trying to adapt the code but keep running into issues ("File Version is too low" or wrong display type.) 

I will keep working on it but am hoping someone has already done it, given how bad the standard webserver is on the ESP32

**Comment by Onno-Dirkzwager** [comment] 2019-06-24 20:24
@makeSmartio 
Although not for direct / local uploads, I have used the ESPAsyncWebServer with the IOTAppStory library. From my personal experience the "File Version is too low or wrong display type" error is nearly always caused by scrambled data after the first few bytes as a result of not being able to "pass" it in quickly enough.

The ESPAsyncWebServer library has an excellent example for firmware uploads. Have you looked at this? Might be a good place to start.

And are you using some sort of a buffer? Or direct upload to serial Nextion?

Neither I or @Nredor have a lot of time at the moment but I would like to revisit this in a couple of weeks and if you havent already, provide an ESPAsyncWebServer example.

**Comment by SomeGuyNamedJay** [comment] 2020-05-29 19:35
Yes. Thank you!

**Comment by makeSmartio** [comment] 2020-05-29 19:36
Yes, thank you!

**Comment by Onno-Dirkzwager** [comment] 2020-05-30 20:00
@makeSmartio thankyou for the feedback. Could you close the issue? It's better for the stats (and I don't have the rights)

**Closed** 2021-03-18 11:04 UTC
